### ISSUE TITLE
feature: if linkedin login

### ISSUE THREAD

**Issue by rishi23root** [rishi23root/resume-editor#10]
on the first login see if the user has logged in from LinkedIn
then load user data from the LinkedIn

tasks 
- [x] handle when logged in from LinkedIn 
- [x] update the Prisma user schema for possible LinkedIn data
- [x] check redirects in new page

**Comment by rishi23root** [comment]
- [ ] may need to update the private metadata for the user 
- [ ]  also need to check for add account event in the application and effect on other features of this

**Comment by maazshakeel** [comment]
Hmm, You want me to give it a go?

**Comment by rishi23root** [comment]
> Hmm, You want me to give it a go?

I would really appreciate your contribution but fortunately, this issue has been resolved 
sorry I missed your comment on this issue, I am generating new issues almost every day, you can   rechose and go with it :)

**Comment by rishi23root** [comment]
fixed with #28 
[f782ebf](https://github.com/rishi23root/resume-editor/commit/f782ebff99bdbe94874566be5531c1b77c57c966)
